# Etapa de construcción
FROM ghcr.io/cirruslabs/flutter:latest AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar solo el archivo de configuración de Flutter primero para instalar dependencias
COPY pubspec.yaml ./

# Ejecutar flutter pub get para instalar dependencias
RUN flutter pub get

# Copiar el archivo pubspec.lock
#USER root
COPY pubspec.lock ./



# Copiar el resto del código fuente de la aplicación
COPY . .

# Construir la aplicación web
RUN flutter build web

# Etapa de producción
FROM nginx:alpine

# Copiar los archivos construidos desde la etapa de construcción
COPY --from=builder /app/build/web /usr/share/nginx/html
COPY --from=builder /app/default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto
EXPOSE 52565

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
